// dbml documentation: https://www.dbml.org/
// schema documentation https://dbdocs.io/thgie/pia_datamodel

// DROP SCHEMA public CASCADE;
// CREATE SCHEMA public;

// Brunner, Kreis - Image-centered
Table Image {
  id int [pk, increment]
  salsah_id int
  oldnr varchar
  signature varchar
  title varchar[]
  original_title varchar[]
  
  date date[]
  salsah_date varchar
  sequence_number varchar
  
  comment int [ref: - Comment.id]
  geography int [ref: > Geography.id]
  collection int [ref: - Collection.id]
  objecttype int [ref: > ObjectType.id]
  model int [ref: > Model.id]
  format int [ref: > Format.id]
}

Table Keyword {
  id int [pk, increment]
  salsah_id int
  label varchar
  alt_label "varchar[]"
  description varchar
  origin varchar
  aat_id int
  aat_url varchar
}

Table Images_Keywords {
  image_id int [ref: > Image.id]
  keyword_id int [ref: > Keyword.id]
}

Table Comment {
  id int [pk, increment]
  comment varchar[]
}

Table Geography {
  id int [pk, increment]
  label varchar
  geonames_id int
  geonames_url varchar
  latitude float
  longitude float
}

Table ObjectType {
  id int [pk, increment]
  label varchar
  comment varchar
  aat_id int
  aat_url varchar
}

Table Model {
  id int [pk, increment]
  label varchar
  comment varchar
  aat_id int
  aat_url varchar
}

Table Format {
  id int [pk, increment]
  label varchar
  comment varchar
}


Table Person {
  id int [pk, increment]
  salsah_id int
  name varchar
  alt_name varchar[]
  title varchar
  family varchar
  gnd_id int
  gnd_url varchar
  birthplace int [ref: > Geography.id]
  deathplace int [ref: > Geography.id]
  birthdate date[]
  deathdate date[]
  salsah_birthdate varchar
  salsah_deathdate varchar
  job varchar[]
  description text
  literature varchar[]
  comment int [ref: - Comment.id]
}

Table Images_Content {
  image_id int [ref: > Image.id]
  person_id int [ref: > Person.id]
}

Table Images_People {
  image_id int [ref: > Image.id]
  person_id int [ref: > Person.id]
}

Table Images_Copyright {
  image_id int [ref: > Image.id]
  person_id int [ref: > Person.id]
}

// Collections
Table Collection {
  id int [pk, increment]
  salsah_id int

  title varchar[]
  label varchar
  signature varchar
  description text
  default_image varchar
  embedded_video varchar

  date date[]
  salsah_date varchar[]

  literature varchar[]
  comment int [ref: - Comment.id]
  indexing int [ref: - Comment.id]
}
Table Collections_People {
  collection_id int [ref: > Collection.id]
  person_id int [ref: > Person.id]
}
Table Album {
  id int [pk, increment]
  salsah_id int

  title varchar
  label varchar
  signature varchar
  description text

  date date[]
  salsah_date varchar[]

  objecttype int [ref: > ObjectType.id]
  collection int [ref: - Collection.id]
  comment int [ref: - Comment.id]
  indexing int [ref: - Comment.id]
}
Table Albums_People {
  album_id int [ref: > Album.id]
  person_id int [ref: > Person.id]
}
Table Albums_Images {
  album_id int [ref: > Album.id]
  image_id int [ref: > Image.id]
}

// Document and Context Objects
// Notes, Protocols, etc
Table Document {
  id int [pk, increment]
  object_type int [ref: > ObjectType.id]
  model int [ref: > Model.id]
  format int [ref: > Format.id]
}

// Map based Model (comming from Atlas)
Table Map {
  id int [pk, increment]
}

Table MapEntry {
  id int [pk, increment]
  map int [ref: > Map.id]
  map_geography int [ref: - MapGeography.id]
  map_legend_entry int [ref: - MapLegendEntry.id]
}

Table MapGeography {
  id int [pk, increment]
  geography int [ref: - Geography.id]
}

Table MapLegend {
  id int [pk, increment]
}

Table MapLegendEntry {
  id int [pk, increment]
}

Table MapLegend_MapLegendEntries {
  map_legend_entry_id int [ref: > MapLegendEntry.id]
  map_legend_id int [ref: - MapLegend.id]
}